
ssh_config_file = /home/acf16449gb/.ssh/config

SSH configuration has been updated.
Host g0185
    HostName g0185
    Port 2222
    StrictHostKeyChecking no

Host g0187
    HostName g0187
    Port 2222
    StrictHostKeyChecking no

Host g0188
    HostName g0188
    Port 2222
    StrictHostKeyChecking no

Host g0194
    HostName g0194
    Port 2222
    StrictHostKeyChecking no

Host g0195
    HostName g0195
    Port 2222
    StrictHostKeyChecking no

Host g0197
    HostName g0197
    Port 2222
    StrictHostKeyChecking no

Host g0198
    HostName g0198
    Port 2222
    StrictHostKeyChecking no

Host g0199
    HostName g0199
    Port 2222
    StrictHostKeyChecking no



ucllm_nedo_dev_train_dir = /home/acf16449gb/ucllm_nedo_prod/train
megatron_deepspeed_dir = /home/acf16449gb/ucllm_nedo_prod/train/Megatron-DeepSpeed

input_tokenizer_file = /groups/gcf51099/crypto_llm/tokenizers/tokenizer_wikipedia_latin_poly_000000_1234_True.model
output_model_dir = /groups/gcf51099/crypto_llm/models/0.latin_wikipedia_poly_000000_1234_True
save_interval = 1000
wandb_entity = yohei-kobashi
wandb_project = encrypted_data_LLM
wandb_tag = other_gpu

Number of GPUs per node: 4
Both /groups/gcf51099/crypto_llm/data/wikipedia_latin_poly_000000_1234_True_text_document.bin and /groups/gcf51099/crypto_llm/data/wikipedia_latin_poly_000000_1234_True_text_document.idx already exist.

hostfile = ./abci_node-8_gpu-32-v100/hostfile_jobid-42821995
g0185 slots=4
g0187 slots=4
g0188 slots=4
g0194 slots=4
g0195 slots=4
g0197 slots=4
g0198 slots=4
g0199 slots=4

[2024-08-09 11:56:29,284] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/acf16449gb/crypto_llm/train/.venv_train/lib/python3.11/site-packages/deepspeed/launcher/runner.py", line 441, in main
    subprocess.check_call(ssh_check_cmd, stderr=subprocess.DEVNULL, stdout=subprocess.DEVNULL, shell=True)
  File "/apps/rocky8/python/3.11.9/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ssh -o PasswordAuthentication=no g0185 hostname' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/acf16449gb/crypto_llm/train/.venv_train/bin/deepspeed", line 6, in <module>
    main()
  File "/home/acf16449gb/crypto_llm/train/.venv_train/lib/python3.11/site-packages/deepspeed/launcher/runner.py", line 443, in main
    raise RuntimeError(
RuntimeError: Using hostfile at ./abci_node-8_gpu-32-v100/hostfile_jobid-42821995 but host=g0185 was not reachable via ssh. If you are running with a single node please remove ./abci_node-8_gpu-32-v100/hostfile_jobid-42821995 or setup passwordless ssh.
